name: Deploy Backend to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "/mnt/user_data/Dai/BE_learning_pali"
          rm: true # Clean old files in the directory before copying

      - name: SSH and Restart Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /mnt/user_data/Dai/BE_learning_pali

            # Setup .env if not exists
            if [ ! -f ".env" ]; then
              echo "PORT=8081" > .env
              echo "DATABASE_URL=postgresql://postgres:palipath2024@postgres:5432/learning_pali?schema=public" >> .env
              echo "PUBLIC_URL=https://api.uydev.io.vn" >> .env
            fi

            # Rebuild and restart containers
            docker compose down || true
            docker compose up -d --build
